POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4OTRjOTU0YjdlOGIxMDQ1NTI2NTQwMCIsImlhdCI6MTc1NDc3MDgyMH0.0hEr8u63SZ1ZEsWjH-4v3rhKe3B1bgoN9XxTWbl58b0

{
    "title": "3432432432",
    "author": "dsfsdfgsdg4",
    "url": "gdsagdsgsda",
    "likes": 5,
    "userId": "6894c954b7e8b10455265400"
}